In [5]:
import pandas as pd
import gzip

# Path to the gzipped CSV file
file_path = 'green_tripdata_2020-10.csv.gz'

# Open the gzipped file
with gzip.open(file_path, 'rt') as file:
    # Load the CSV file into a Pandas DataFrame
    df = pd.read_csv(file)

# Display the DataFrame
df.head(10)

C:\cygwin64\tmp\ipykernel_13268\1168444758.py:10: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,extra,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge
0,2.0,2020-10-01 00:31:19,2020-10-01 00:34:55,N,1.0,7,7,1.0,0.79,5.0,0.5,0.5,1.58,0.0,NaN,0.3,7.88,1.0,1.0,0.00
1,2.0,2020-10-01 00:42:12,2020-10-01 00:43:51,N,1.0,179,7,1.0,0.50,4.0,0.5,0.5,0.00,0.0,NaN,0.3,5.30,2.0,1.0,0.00
2,2.0,2020-10-01 00:53:09,2020-10-01 00:55:39,N,1.0,179,223,1.0,0.60,4.0,0.5,0.5,1.06,0.0,NaN,0.3,6.36,1.0,1.0,0.00
3,1.0,2020-10-01 00:12:29,2020-10-01 00:20:08,N,1.0,134,216,2.0,4.40,13.5,0.5,0.5,0.00,0.0,NaN,0.3,14.80,2.0,1.0,0.00
4,1.0,2020-10-01 00:32:38,2020-10-01 00:43:02,N,1.0,82,7,1.0,2.90,10.5,0.5,0.5,0.00,0.0,NaN,0.3,11.80,2.0,1.0,0.00
5,2.0,2020-10-01 00:04:50,2020-10-01 00:13:34,N,1.0,75,42,1.0,2.65,9.5,0.5,0.5,0.00,0.0,NaN,0.3,10.80,2.0,1.0,0.00
6,2.0,2020-10-01 00:49:30,2020-10-01 01:09:03,N,1.0,42,51,1.0,11.48,33.0,0.5,0.5,0.00,0.0,NaN,0.3,34.30,2.0,1.0,0.00
7,2.0,2020-10-01 00:54:35,2020-10-01 01:03:43,N,1.0,25,80,1.0,4.12,13.5,0.5,0.5,4.44,0.0,NaN,0.3,19.24,1.0,1.0,0.00
8,2.0,2020-10-01 01:00:05,2020-10-01 01:07:56,N,1.0,74,43,1.0,2.24,9.0,0.5,0.5,3.92,0.0,NaN,0.3,16.97,1.0,1.0,2.75
9,1.0,2020-10-01 00:46:58,2020-10-01 00:58:36,N,1.0,260,146,1.0,2.70,11.0,0.5,0.5,3.05,0.0,NaN,0.3,15.35,1.0,1.0,0.00

In [8]:
print(df.dtypes)

VendorID                 float64
lpep_pickup_datetime      object
lpep_dropoff_datetime     object
store_and_fwd_flag        object
RatecodeID               float64
PULocationID               int64
DOLocationID               int64
passenger_count          float64
trip_distance            float64
fare_amount              float64
extra                    float64
mta_tax                  float64
tip_amount               float64
tolls_amount             float64
ehail_fee                float64
improvement_surcharge    float64
total_amount             float64
payment_type             float64
trip_type                float64
congestion_surcharge     float64
dtype: object

In [9]:
num_unique_values = df['VendorID'].nunique()
print("Number of different values:", num_unique_values)

Number of different values: 2